accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    url(r'^change-password/', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^update/', views.UpdateProfile.as_view(), name='update'),
    url(r'^setting/', views.SettingView.as_view(), name='setting')
]

pages/urls.py
from django.conf.urls import url

from . import views

app_name = 'pages'
urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home')
]

seotool/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password-reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password-reset/done', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_complete'),
    url('^', include('pages.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^business/', include('business.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User


class UpdateProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
        )

accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

# Create your views here.
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse
from django.views.generic import TemplateView, UpdateView


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'


class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    model = User

    template_name = 'accounts/change_password.html'

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        messages.success(self.request, 'Password Successfully changed')
        return reverse('accounts:profile')


class UpdateProfile(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['first_name', 'last_name']

    template_name = 'accounts/update.html'

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        messages.success(self.request, 'Profile Updated Successfully')
        return reverse('accounts:profile')


class SettingView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/setting.html'

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="page-header page-header-small" filter-color="orange">

    {% include 'profile_badge.html' %}


        </div>
        <div class="section">
            <div class="container">
                <div class="button-container">
                    <a href="{% url 'accounts:update' %}" class="btn btn-primary btn-round btn-lg">Update</a>
                    <a href="{% url 'accounts:change_password' %}" class="btn btn-primary btn-round btn-lg">Change Password</a>
                </div>
                <h3 class="title">Change Password</h3>


                <div class="container">
                    <div class="row">
                        <div class="col-md-12 col-lg-10 col-xl-8 ml-auto mr-auto">
                            <!-- Tabs with Background on Card -->
                            <div class="card">
                                <div class="card-body">
                                    <!-- Tab panes -->
                                    <div class="tab-content text-center">


                                        <form method="post">
                                            {% csrf_token %}

                                            <div class="row">
                                                <div class="col-md-12">
                                                    {{ form.non_field_errors }}
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-3 col-sm-12 text-right vertical-middle">
                                                    <label>Current Password</label>
                                                </div>
                                                <div class="col-md-9 col-sm-12">
                                                    <div class="input-group">
                                                        <span class="input-group-addon">
                                                            <i class="fa fa-asterisk"></i>
                                                        </span>
                                                        <input type="password" id="id_old_password" name="old_password" class="form-control" placeholder="Current Password" required>
                                                    </div>
                                                    {{ form.old_password.errors }}
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-3 col-sm-12 text-right vertical-middle">
                                                    <label>New Password</label>
                                                </div>
                                                <div class="col-md-9 col-sm-12">
                                                    <div class="input-group">
                                                        <span class="input-group-addon">
                                                            <i class="fa fa-asterisk"></i>
                                                        </span>
                                                        <input type="password" id="id_new_password1" name="new_password1" class="form-control" placeholder="New Password" required>
                                                    </div>
                                                    {{ form.new_password1.errors }}

                                                    {% if form.new_password1.help_text %}
                                                    <div class="alert alert-info text-left form-help">
                                                        {{ form.new_password1.help_text|safe }}
                                                    </div>
                                                    {% endif %}

                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-3 col-sm-12 text-right vertical-middle">
                                                    <label>Confirm Password</label>
                                                </div>
                                                <div class="col-md-9 col-sm-12">
                                                    <div class="input-group">
                                                        <span class="input-group-addon">
                                                            <i class="fa fa-asterisk"></i>
                                                        </span>
                                                        <input type="password" id="id_new_password2" name="new_password2" class="form-control" placeholder="Confirm Password" required>
                                                    </div>
                                                    {{ form.new_password2.errors }}
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <button class="btn btn-success btn-round pull-right">Change Password</button>
                                                </div>
                                            </div>


                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!-- End Tabs on plain Card -->
                        </div>
                    </div>
                </div>




            </div>
        </div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="page-header page-header-small" filter-color="orange">

            {% include 'profile_badge.html' %}

        </div>
        <div class="section">
            <div class="container">
                <div class="button-container">
                    <a href="{% url 'accounts:update' %}" class="btn btn-primary btn-round btn-lg">Update</a>
                    <a href="{% url 'accounts:change_password' %}" class="btn btn-primary btn-round btn-lg">Change Password</a>
                </div>
                <h3 class="title">About me</h3>
                <h5 class="description">An artist of considerable range, Ryan — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music, giving it a warm, intimate feel with a solid groove structure. An artist of considerable range.</h5>
                <div class="row">
                    <div class="col-md-6 ml-auto mr-auto">
                        <h4 class="title text-center">My Portfolio</h4>
                        <div class="nav-align-center">
                            <ul class="nav nav-pills nav-pills-primary" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="#profile" role="tablist">
                                        <i class="now-ui-icons design_image"></i>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" data-toggle="tab" href="#home" role="tablist">
                                        <i class="now-ui-icons location_world"></i>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="#messages" role="tablist">
                                        <i class="now-ui-icons sport_user-run"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- Tab panes -->
                    <div class="tab-content gallery">
                        <div class="tab-pane active" id="home" role="tabpanel">
                            <div class="col-md-10 ml-auto mr-auto">
                                <div class="row collections">
                                    <div class="col-md-6">
                                        <img src="{% static 'img/bg1.jpg' %}" alt="" class="img-raised">
                                        <img src="{% static 'img/bg3.jpg' %}" alt="" class="img-raised">
                                    </div>
                                    <div class="col-md-6">
                                        <img src="{% static 'img/bg8.jpg' %}" alt="" class="img-raised">
                                        <img src="{% static 'img/bg7.jpg' %}" alt="" class="img-raised">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="profile" role="tabpanel">
                            <div class="col-md-10 ml-auto mr-auto">
                                <div class="row collections">
                                    <div class="col-md-6">
                                        <img src="{% static 'img/bg6.jpg' %}" class="img-raised">
                                        <img src="{% static 'img/bg11.jpg' %}" alt="" class="img-raised">
                                    </div>
                                    <div class="col-md-6">
                                        <img src="{% static 'img/bg7.jpg' %}" alt="" class="img-raised">
                                        <img src="{% static 'img/bg8.jpg' %}" alt="" class="img-raised">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="messages" role="tabpanel">
                            <div class="col-md-10 ml-auto mr-auto">
                                <div class="row collections">
                                    <div class="col-md-6">
                                        <img src="{% static 'img/bg3.jpg' %}" alt="" class="img-raised">
                                        <img src="{% static 'img/bg8.jpg' %}" alt="" class="img-raised">
                                    </div>
                                    <div class="col-md-6">
                                        <img src="{% static 'img/bg7.jpg' %}" alt="" class="img-raised">
                                        <img src="{% static 'img/bg6.jpg' %}" class="img-raised">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% load avatar_tags %}

{% block content %}
<div class="page-header page-header-small" filter-color="orange">

    {% include 'profile_badge.html' %}

        </div>
        <div class="section">
            <div class="container">
                <div class="button-container">
                    <a href="{% url 'accounts:update' %}" class="btn btn-primary btn-round btn-lg">Update</a>
                    <a href="{% url 'accounts:change_password' %}" class="btn btn-primary btn-round btn-lg">Change Password</a>
                </div>
                <h3 class="title">Update Profile</h3>


                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-lg-4 col-xl-4 ml-auto mr-auto">
                            <p class="category">Change Avatar</p>
                            <!-- Nav tabs -->
                            <div class="card">
                                <div class="card-body">
                                    <!-- Tab panes -->
                                    <div class="tab-content text-center">

                                        <form method="post" enctype="multipart/form-data" action="{% url 'avatar_add' %}">
                                            {% csrf_token %}

                                        <div class="photo-container profile-picture-change">
                                            {% avatar user 400 class="img-circle" %}
                                        </div>

                                            <input name="avatar" id="id_avatar" type="file">

                                            {% if request.user|has_avatar == False %}
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="alert alert-info">
                                                            You haven't uploaded an avatar yet. Please upload one now.
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endif %}

                                            <a href="{% url 'avatar_change' %}" class="btn btn-success">Change Avatar</a>
                                        <button class="btn btn-success">Change Avatar</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8 col-lg-8 col-xl-8 ml-auto mr-auto">
                            <p class="category">Profile Detail</p>
                            <!-- Tabs with Background on Card -->
                            <div class="card">
                                <div class="card-body">
                                    <!-- Tab panes -->
                                    <div class="tab-content text-center">


                                        <form method="post">
                                            {% csrf_token %}

                                            <div class="row">
                                                <div class="col-md-2 col-sm-12 text-right vertical-middle">
                                                    <label>First Name</label>
                                                </div>
                                                <div class="col-md-10 col-sm-12">
                                                    <div class="input-group">
                                                        <span class="input-group-addon">
                                                            <i class="fa fa-user-circle"></i>
                                                        </span>
                                                        <input name="first_name" value="{{ request.user.first_name }}" class="form-control" placeholder="First Name">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-2 col-sm-12 text-right vertical-middle">
                                                    <label>Last Name</label>
                                                </div>
                                                <div class="col-md-10 col-sm-12">
                                                    <div class="input-group">
                                                        <span class="input-group-addon">
                                                            <i class="fa fa-user-circle"></i>
                                                        </span>
                                                        <input name="last_name" value="{{ request.user.last_name }}" class="form-control" placeholder="Last Name">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <button class="btn btn-success btn-round pull-right">Update</button>
                                                </div>
                                            </div>


                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!-- End Tabs on plain Card -->
                        </div>
                    </div>
                </div>




            </div>
        </div>
{% endblock content %}