business/urls.py
from django.conf.urls import url

from business.views3 import BusinessList, BusinessDetail, BusinessCreate, BusinessUpdate, BusinessDelete

app_name = 'business'
urlpatterns = [
    url(r'add/$', BusinessCreate.as_view(), name='add'),
    url(r'^$', BusinessList.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', BusinessDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/update$', BusinessUpdate.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete$', BusinessDelete.as_view(), name='delete'),
]

pages/urls.py
from django.conf.urls import url

from . import views

app_name = 'pages'
urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home')
]

seotool/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password-reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password-reset/done', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_complete'),
    url('^', include('pages.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^business/', include('business.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

business/models.py
from django.contrib.auth.models import User
from django.db import models
from state.models import State


# Create your models here.

class BusinessType(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField('date created', auto_now_add=True)
    modified = models.DateTimeField('last modified', auto_now=True)

    class Meta:
        db_table = 'business_types'

    def __str__(self):
        return self.title


class Business(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    business_type = models.ForeignKey(BusinessType, on_delete=models.CASCADE)
    created = models.DateTimeField('date created', auto_now_add=True)
    modified = models.DateTimeField('last modified', auto_now=True)

    class Meta:
        verbose_name = 'business'
        verbose_name_plural = 'businesses'
        db_table = 'businesses'

    def __str__(self):
        return self.name


class BusinessAddress(models.Model):
    business = models.OneToOneField(Business, on_delete=models.CASCADE)
    line_1 = models.CharField(max_length=200)
    line_2 = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.ForeignKey(State, on_delete=models.PROTECT)
    postal_code = models.CharField(max_length=15)
    created = models.DateTimeField('date created', auto_now_add=True)
    modified = models.DateTimeField('last modified', auto_now=True)

    class Meta:
        verbose_name = 'business address'
        verbose_name_plural = 'business addresses'
        db_table = 'business_addresses'

    def __str__(self):
        return '%s, %s, %s, %s' % (self.line_1, self.line_2, self.city, self.state)


class BusinessEmail(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    email = models.EmailField(unique=True, default=None)
    created = models.DateTimeField('date created', auto_now_add=True)
    modified = models.DateTimeField('last modified', auto_now=True)

    class Meta:
        db_table = 'business_emails'

    def __str__(self):
        return self.email


class BusinessPhone(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, default=None)
    created = models.DateTimeField('date created', auto_now_add=True)
    modified = models.DateTimeField('last modified', auto_now=True)

    class Meta:
        db_table = 'business_phones'

    def __str__(self):
        return self.phone_number


class BusinessWebsite(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    website = models.URLField(max_length=100, default=None)
    created = models.DateTimeField('date created', auto_now_add=True)
    modified = models.DateTimeField('last modified', auto_now=True)

    class Meta:
        db_table = 'business_websites'

    def __str__(self):
        return self.url

business/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from business.Forms import BusinessAddressFormSet, BusinessEmailFormSet, BusinessPhoneFormSet, BusinessWebsiteFormSet, \
    BusinessForm
from business.models import Business


class BusinessList(LoginRequiredMixin, ListView):
    model = Business
    context_object_name = 'list_of_user_businesses'


class BusinessDetail(LoginRequiredMixin, DetailView):
    context_object_name = 'business'
    queryset = Business.objects.all()


class BusinessCreate(LoginRequiredMixin, CreateView):
    model = Business
    form_class = BusinessForm

    def get_context_data(self, **kwargs):
        data = super(BusinessCreate, self).get_context_data(**kwargs)

        if self.request.POST:
            data['business_address'] = BusinessAddressFormSet(self.request.POST)
            data['business_email'] = BusinessEmailFormSet(self.request.POST)
            data['business_phone'] = BusinessPhoneFormSet(self.request.POST)
            data['business_website'] = BusinessWebsiteFormSet(self.request.POST)
        else:
            data['business_address'] = BusinessAddressFormSet()
            data['business_email'] = BusinessEmailFormSet()
            data['business_phone'] = BusinessPhoneFormSet()
            data['business_website'] = BusinessWebsiteFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        form.instance.user = self.request.user
        business_address = context['business_address']
        business_email = context['business_email']
        business_phone = context['business_phone']
        business_website = context['business_website']
        with transaction.atomic():
            self.object = form.save()

            if business_address.is_valid():
                messages.success(self.request, 'Business address is valid')
                business_address.save()

            if business_email.is_valid():
                messages.success(self.request, 'Email is valid')
                business_email.save()

            if business_phone.is_valid():
                messages.success(self.request, 'Phone is valid')
                business_phone.save()
            else:
                messages.success(self.request, 'Phone is valid')

            if business_website.is_valid():
                messages.success(self.request, 'Website is valid')
                business_website.save()

        return super(BusinessCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Business Added Successfully')
        return reverse('business:list')


class BusinessUpdate(LoginRequiredMixin, UpdateView):
    model = Business


class BusinessDelete(LoginRequiredMixin, DeleteView):
    model = Business

business/templates/business/business_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>Business Detail</h2>

    <ul>

    </ul>

{% endblock content %}

business/templates/business/business_form.html
{% extends 'base.html' %}
{% load static %}
{% load avatar_tags %}
{% load widget_tweaks %}

{% block content %}


        <div class="page-header page-header-small height-30vh">
            <div class="page-header-image" data-parallax="true" style="background-image: url('{% static 'img/bg6.jpg' %}');">
            </div>
            <div class="container">
                <div class="content-center cstm-page-header">
                    <h1 class="title">Add Businesses</h1>
                </div>
            </div>
        </div>


        <div class="section section-page section-business-card">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <a href="{% url 'business:list' %}" class="btn btn-success btn-round pull-right">
                            <i class="fa fa-plus"></i>
                            List All Business
                        </a>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <!-- Tabs with Background on Card -->
                        <form class="card" method="post">
                            {% csrf_token %}

                            <div class="row">
                                <div class="col-md-12">
                                    {{ form.errors }}
                                    {{ form.non_field_errors }}
                                </div>
                            </div>

                            <div class="card-body">
                                <!-- Tab panes -->

                                <p class="description">
                                    Business Information
                                </p>
                                <div class="row">
                                    <div class="col-lg-12 text-center col-md-12 ml-auto mr-auto">
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-building-o"></i>
                                            </span>
                                            {% render_field form.name class='form-control' placeholder='Business Title' %}
                                            {{ form.name.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-briefcase"></i>
                                            </span>
                                            {% render_field form.business_type class='form-control' %}
                                            {{ form.business_type.errors }}
                                        </div>
                                    </div>
                                </div>

                                <p class="description">
                                    Business Address
                                    {{ business_address.management_form }}
                                </p>
                                <div class="row">
                                    <div class="col-lg-12 text-center col-md-12 ml-auto mr-auto">
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-address-card-o"></i>
                                            </span>
                                            {% render_field business_address.form.line_1 class='form-control' placeholder=business_address.form.line_1.label %}
                                            {{ business_address.form.line_1.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-address-card-o"></i>
                                            </span>
                                            {% render_field business_address.form.line_2 class='form-control' placeholder=business_address.form.line_2.label %}
                                            {{ business_address.form.line_2.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-map-marker"></i>
                                            </span>
                                            {% render_field business_address.form.city class='form-control' placeholder=business_address.form.city.label %}
                                            {{ business_address.form.city.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-location-arrow"></i>
                                            </span>
                                            {% render_field business_address.form.state class='form-control' %}
                                            {{ business_address.form.state.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-address-card-o"></i>
                                            </span>
                                            {% render_field business_address.form.postal_code class='form-control' placeholder=business_address.form.postal_code.label %}
                                            {{ business_address.form.postal_code.errors }}
                                        </div>
                                    </div>
                                </div>

                                <p class="description">
                                    Contact Information
                                    {{ business_email.management_form }}
                                    {{ business_phone.management_form }}
                                    {{ business_website.management_form }}
                                </p>
                                <div class="row">
                                    <div class="col-lg-12 text-center col-md-12 ml-auto mr-auto">
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-at"></i>
                                            </span>
                                            {% render_field business_email.form.email class='form-control' placeholder=business_email.form.email.label %}
                                            {{ business_email.form.email.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-phone"></i>
                                            </span>
                                            {% render_field business_phone.form.phone_number class='form-control' placeholder=business_phone.form.phone_number.label %}
                                            {{ business_phone.form.phone_number.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-globe"></i>
                                            </span>
                                            {% render_field business_website.form.website class='form-control' placeholder=business_website.form.website.label %}
                                            {{ business_website.form.website.errors }}
                                        </div>
                                        <div class="send-button">
                                            <button class="btn btn-primary btn-round btn-block btn-lg">Add Business</button>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </form>
                        </div>
                        <!-- End Tabs on plain Card -->
                    </div>
                </div>

            </div>
        </div>


{% endblock content %}


{% block javascript %}


{% endblock javascript %}

business/templates/business/business_form2.html
{% extends 'base.html' %}
{% load static %}
{% load avatar_tags %}
{% load widget_tweaks %}

{% block content %}


        <div class="page-header page-header-small height-30vh">
            <div class="page-header-image" data-parallax="true" style="background-image: url('{% static 'img/bg6.jpg' %}');">
            </div>
            <div class="container">
                <div class="content-center cstm-page-header">
                    <h1 class="title">Add Businesses</h1>
                </div>
            </div>
        </div>


        <div class="section section-page section-business-card">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <a href="{% url 'business:list' %}" class="btn btn-success btn-round pull-right">
                            <i class="fa fa-plus"></i>
                            List All Business
                        </a>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <!-- Tabs with Background on Card -->
                        <form class="card" method="post">
                            {% csrf_token %}

                            <div class="row">
                                <div class="col-md-12">
                                    {{ form.non_field_errors }}
                                </div>
                            </div>

                            <div class="card-body">
                                <!-- Tab panes -->

                                <p class="description">
                                    Business Information
                                </p>
                                <div class="row">
                                    <div class="col-lg-12 text-center col-md-12 ml-auto mr-auto">
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-building-o"></i>
                                            </span>
                                            {% render_field form.name class='form-control' placeholder='Business Title' %}
                                            {{ form.name.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-briefcase"></i>
                                            </span>
                                            {% render_field form.business_type class='form-control' %}
                                            {{ form.business_type.errors }}
                                        </div>
                                    </div>
                                </div>

                                <p class="description">
                                    Business Address
                                    {{ business_address.management_form }}
                                </p>
                                <div class="row">
                                    <div class="col-lg-12 text-center col-md-12 ml-auto mr-auto">
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-address-card-o"></i>
                                            </span>
                                            {% render_field business_address.form.line_1 class='form-control' placeholder=business_address.form.line_1.label %}
                                            {{ business_address.form.line_1.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-address-card-o"></i>
                                            </span>
                                            {% render_field business_address.form.line_2 class='form-control' placeholder=business_address.form.line_2.label %}
                                            {{ business_address.form.line_2.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-map-marker"></i>
                                            </span>
                                            {% render_field business_address.form.city class='form-control' placeholder=business_address.form.city.label %}
                                            {{ business_address.form.city.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-location-arrow"></i>
                                            </span>
                                            {% render_field business_address.form.state class='form-control' %}
                                            {{ business_address.form.state.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-address-card-o"></i>
                                            </span>
                                            {% render_field business_address.form.postal_code class='form-control' placeholder=business_address.form.postal_code.label %}
                                            {{ business_address.form.postal_code.errors }}
                                        </div>
                                    </div>
                                </div>

                                <p class="description">
                                    Contact Information
                                    {{ business_email.management_form }}
                                    {{ business_phone.management_form }}
                                    {{ business_website.management_form }}
                                </p>
                                <div class="row">
                                    <div class="col-lg-12 text-center col-md-12 ml-auto mr-auto">
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-at"></i>
                                            </span>
                                            {% render_field business_email.form.email class='form-control' placeholder=business_email.form.email.label %}
                                            {{ business_email.form.email.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-phone"></i>
                                            </span>
                                            {% render_field business_phone.form.phone_number class='form-control' placeholder=business_phone.form.phone_number.label %}
                                            {{ business_phone.form.phone_number.errors }}
                                        </div>
                                        <div class="input-group input-lg">
                                            <span class="input-group-addon">
                                                <i class="fa fa-globe"></i>
                                            </span>
                                            {% render_field business_website.form.website class='form-control' placeholder=business_website.form.website.label %}
                                            {{ business_website.form.website.errors }}
                                        </div>
                                        <div class="send-button">
                                            <button class="btn btn-primary btn-round btn-block btn-lg">Add Business</button>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </form>
                        </div>
                        <!-- End Tabs on plain Card -->
                    </div>
                </div>

            </div>
        </div>


{% endblock content %}


{% block javascript %}


{% endblock javascript %}

business/templates/business/business_list.html
{% extends 'base.html' %}
{% load static %}
{% load avatar_tags %}

{% block content %}

{% for a in queryset %} {{ a }} {% endfor %}




        <div class="page-header page-header-small height-30vh">
            <div class="page-header-image" data-parallax="true" style="background-image: url('{% static 'img/bg6.jpg' %}');">
            </div>
            <div class="container">
                <div class="content-center cstm-page-header">
                    <h1 class="title">My Businesses</h1>
                </div>
            </div>
        </div>



        <div class="section section-page section-business-card">

            <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <a href="{% url 'business:add' %}" class="btn btn-success btn-round pull-right">
                        <i class="fa fa-plus"></i>
                        Add Business
                    </a>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4 col-lg-4 col-xl-4 col-sm-6 col-xs-12 ml-auto mr-auto">
                    <!-- Tabs with Background on Card -->
                    <div class="card">
                        <ul class="nav nav-tabs nav-tabs-neutral business-title" role="tablist" data-background-color="orange">
                            <li class="nav-item">
                                <a class="nav-link active no-border" data-toggle="tab" href="#detail" role="tab" aria-expanded="true">Home</a>
                            </li>
                        </ul>
                        <div class="card-body">
                            <!-- Tab panes -->
                            <div class="tab-content text-center">
                                <div class="tab-pane active" role="tabpanel" aria-expanded="true">

                                    <div class="row">
                                        <div class="col-md-4 col-sm-12 text-center">
                                            <div class="business-logo-holder">
                                                <img src="{% avatar_url user 400 %}" class="img-responsive" alt="">
                                            </div>
                                        </div>
                                        <div class="col-md-8 col-sm-12">
                                            <p>This is business text</p>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="card-footer no-padding">
                            <div class="row">
                                <div class="col-sm-6 col-6 no-padding">
                                    <button type="button" class="btn btn-warning btn-block btn-flat">
                                        <i class="fa fa-pencil"></i>
                                        <span class="hidden-xs hidden-sm">Edit</span>
                                    </button>
                                </div>
                                <div class="col-sm-6 col-6 no-padding">
                                    <button type="button" class="btn btn-danger btn-block btn-flat">
                                        <i class="fa fa-trash-o"></i>
                                        <span class="hidden-lg hidden-md">Delete</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End Tabs on plain Card -->
                </div>


            </div>
                </div>



        </div>

        <div class="section section-about-us">
            <div class="col-md-4 col-md-offset-4">
                <a href="#" class="btn btn-success btn-round btn-block">
                    <i class="fa fa-plus"></i>
                    Add Business
                </a>
            </div>
        </div>

{% endblock content %}