accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    url(r'^change-password/', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^update/', views.UpdateProfile.as_view(), name='update'),
    url(r'^setting/', views.SettingView.as_view(), name='setting')
]

pages/urls.py
from django.conf.urls import url

from . import views

app_name = 'pages'
urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home')
]

seotool/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password-reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password-reset/done', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_complete'),
    url('^', include('pages.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^business/', include('business.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

templates/base.html
{% load static %}
{% load avatar_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="./assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        {% block title %} SEO Tool {% endblock %}
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/now-ui-kit.css' %}" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="{% static 'css/demo.css' %}" />
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
</head>

{% if request.resolver_match.app_name == 'accounts' %}
    <body class="profile-page sidebar-collapse">
{% else %}
    <body class="index-page sidebar-collapse">
{% endif %}


    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent " color-on-scroll="100">
        <div class="container">
            <div class="navbar-translate">

                {% include 'element/website_title.html' %}

                <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="{% static 'img/blurred-image-1.jpg' %}">
                <ul class="navbar-nav">

                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" data-toggle="dropdown" id="navbarDropdownUserMenu" href="#">
                                    {% avatar user 400 width="100%" height="100%" class="rounded-circle navigation-avatar" alt="{{ request.user.get_full_name|default:request.user.username }}" %}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownUserMenu">

                                    {% if request.user.is_superuser == True %}
                                        <div class="dropdown-header">Super Admin Menu</div>
                                        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                                    {% endif %}

                                    <div class="dropdown-header">Settings</div>
                                    <a class="dropdown-item" href="{% url 'accounts:setting' %}">Settings</a>
                                    <div class="dropdown-header">{{ request.user.get_full_name|default:request.user.username }}</div>
                                    <a class="dropdown-item" href="{% url 'accounts:profile' %}">My Profile</a>
                                    <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                                </ul>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">
                                <i class="now-ui-icons ui-1_lock-circle-open"></i>
                                <p>Login</p>
                            </a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->
    <div class="wrapper">


        <!-- block content -->

        {% block content %}

        {% endblock %}

        <!-- end block content -->



        <!--  End Modal -->
        <footer class="footer" data-background-color="black">
            {% include 'element/footer.html' %}
        </footer>

        {% include 'element/flash_message.html' %}

    </div>
</body>
<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="{% static 'js/plugins/bootstrap-datepicker.js' %}" type="text/javascript"></script>
<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/now-ui-kit.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        // the body of this function is in assets/js/now-ui-kit.js
        nowuiKit.initSliders();
    });

    function scrollToDownload() {

        if ($('.section-download').length != 0) {
            $("html, body").animate({
                scrollTop: $('.section-download').offset().top
            }, 1000);
        }
    }
</script>

    {% block javascript %}

        {# javascript code goes here #}

    {% endblock javascript %}

</html>

templates/base_login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        {% block title %} Auth Login {% endblock %} | SEO Tool
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{% static 'css/demo.css' %}" rel="stylesheet" />
</head>

<body class="login-page sidebar-collapse">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent " color-on-scroll="400">
        <div class="container">
            <div class="dropdown button-dropdown">
                <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
                    <span class="button-bar"></span>
                    <span class="button-bar"></span>
                    <span class="button-bar"></span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-header">Auth Menu</a>
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'password_reset' %}">Forgot Password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-header">Navigation</a>
                    <a class="dropdown-item" href="{% url 'pages:home' %}">Home</a>
                    <a class="dropdown-item" href="{% url 'pages:home' %}">About</a>
                    <a class="dropdown-item" href="{% url 'pages:home' %}">Contact</a>
                </div>
            </div>
            <div class="navbar-translate">

                {% include 'element/website_title.html' %}

                <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>

        </div>
    </nav>
    <!-- End Navbar -->
    <div class="page-header" filter-color="orange">
        <div class="page-header-image" style="background-image:url({% static 'img/login.jpg' %})"></div>
        <div class="container">

            {% block content %}

            {% endblock %}

        </div>
        <footer class="footer">

            {% include 'element/footer.html' %}

        </footer>
    </div>
</body>
<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="{% static 'js/plugins/bootstrap-datepicker.js' %}" type="text/javascript"></script>
<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/now-ui-kit.js' %}" type="text/javascript"></script>

</html>